=== MehdiRtal/FileHippoDownloader/schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"properties": {
		"spotify": {
			"type": "object",
			"properties": {
				"version": {
					"type": "string"
				},
				"installer": {
					"type": "string"
				},
				"arguments": {
					"type": "string"
				}
			},
			"required": [
				"version",
				"installer",
				"arguments"
			]
		},
		"anydesk": {
			"type": "object",
			"properties": {
				"version": {
					"type": "string"
				},
				"installer": {
					"type": "string"
				},
				"arguments": {
					"type": "string"
				}
			},
			"required": [
				"version",
				"installer",
				"arguments"
			]
		},
		"7zip-64": {
			"type": "object",
			"properties": {
				"version": {
					"type": "string"
				},
				"installer": {
					"type": "string"
				}
			},
			"required": [
				"version",
				"installer"
			]
		},
		"whatsapp-64": {
			"type": "object",
			"properties": {
				"version": {
					"type": "string"
				},
				"installer": {
					"type": "string"
				}
			},
			"required": [
				"version",
				"installer"
			]
		},
		"discord": {
			"type": "object",
			"properties": {
				"version": {
					"type": "string"
				},
				"installer": {
					"type": "string"
				}
			},
			"required": [
				"version",
				"installer"
			]
		},
		"vlc-media-player-64": {
			"type": "object",
			"properties": {
				"version": {
					"type": "string"
				},
				"installer": {
					"type": "string"
				}
			},
			"required": [
				"version",
				"installer"
			]
		},
		"winscp": {
			"type": "object",
			"properties": {
				"version": {
					"type": "string"
				},
				"installer": {
					"type": "string"
				}
			},
			"required": [
				"version",
				"installer"
			]
		},
		"sharex": {
			"type": "object",
			"properties": {
				"version": {
					"type": "string"
				},
				"installer": {
					"type": "string"
				}
			},
			"required": [
				"version",
				"installer"
			]
		},
		"open-broadcaster-software": {
			"type": "object",
			"properties": {
				"version": {
					"type": "string"
				},
				"installer": {
					"type": "string"
				}
			},
			"required": [
				"version",
				"installer"
			]
		},
		"virtualbox": {
			"type": "object",
			"properties": {
				"version": {
					"type": "string"
				},
				"installer": {
					"type": "string"
				},
				"arguments": {
					"type": "string"
				}
			},
			"required": [
				"version",
				"installer",
				"arguments"
			]
		},
		"libre-office": {
			"type": "object",
			"properties": {
				"version": {
					"type": "string"
				},
				"installer": {
					"type": "string"
				}
			},
			"required": [
				"version",
				"installer"
			]
		},
		"microsoft-powertoys": {
			"type": "object",
			"properties": {
				"version": {
					"type": "string"
				},
				"installer": {
					"type": "string"
				},
				"arguments": {
					"type": "string"
				}
			},
			"required": [
				"version",
				"installer",
				"arguments"
			]
		},
		"qbittorrent-64": {
			"type": "object",
			"properties": {
				"version": {
					"type": "string"
				},
				"installer": {
					"type": "string"
				}
			},
			"required": [
				"version",
				"installer"
			]
		}
	},
	"required": [
		"spotify",
		"anydesk",
		"7zip-64",
		"whatsapp-64",
		"discord",
		"vlc-media-player-64",
		"winscp",
		"sharex",
		"open-broadcaster-software",
		"virtualbox",
		"libre-office",
		"microsoft-powertoys",
		"qbittorrent-64"
	]
}

=== MehdiRtal/FileHippoDownloader/config.json
{
    "spotify": {
        "version": "1.1.74.631",
        "installer": "custom",
        "arguments": "/extract \"C:\\Program Files\\Spotify\""
    },
    "anydesk": {
        "version": "7.0.4",
        "installer": "custom",
        "arguments": "--install \"C:\\Program Files (x86)\\AnyDesk\" --silent --create-desktop-icon --create-shortcuts --start-with-win"
    },
    "7zip-64": {
        "version": "19.00",
        "installer": "nsis"
    },
    "whatsapp-64": {
        "version": "2.2108.8",
        "installer": "squirrel"
    },
    "discord": {
        "version": "1.0.9003",
        "installer": "squirrel"
    },
    "vlc-media-player-64": {
        "version": "3.0.12",
        "installer": "nsis"
    },
    "winscp": {
        "version": "5.19.4",
        "installer": "innosetup"
    },
    "sharex": {
        "version": "13.6.1",
        "installer": "innosetup"
    },
    "open-broadcaster-software": {
        "version": "27.1.3",
        "installer": "nsis"
    },
    "virtualbox": {
        "version": "6.1.30",
        "installer": "custom",
        "arguments": "--silent --ignore-reboot"
    },
    "libre-office": {
        "version": "6.2.4",
        "installer": "msi"
    },
    "microsoft-powertoys": {
        "version": "0.51.1",
        "installer": "custom",
        "arguments": "/install /quiet /norestart"
    },
    "qbittorrent-64": {
        "version": "4.3.4.1",
        "installer": "nsis"
    }
}
